"""update: comments table

Revision ID: 50f07983077e
Revises: 5d9709ed28b4
Create Date: 2023-07-28 10:16:21.725383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f07983077e'
down_revision = '5d9709ed28b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('ad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'ads', ['ad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'ad_id')
    # ### end Alembic commands ###
