"""add: one-to-many relationship for users-ads

Revision ID: 92e8607ed272
Revises: ab5ae3333557
Create Date: 2023-07-27 13:42:22.033149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e8607ed272'
down_revision = 'ab5ae3333557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
