"""second migration, add: ads

Revision ID: ab5ae3333557
Revises: d971a19e5fe0
Create Date: 2023-07-27 12:48:54.797318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5ae3333557'
down_revision = 'd971a19e5fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
